### ISSUE TITLE
Example with `eframe`

### ISSUE THREAD

**Issue by ijsnow** [amrbashir/global-hotkey#15]
Could you provide an example with [eframe](https://docs.rs/eframe)? It has an event loop running internally. Also could you explain why it needs to be running in an event loop? Based on the examples in the readme, [this sort of snippet](https://github.com/tauri-apps/global-hotkey/issues/8) should work.

**Comment by amrbashir** [comment]
Without an event loop, the OS won't send any events for the hotkeys you register. Anyways, the repo now has an `egui` example but it is not perfect, feel free to PR a better version if you know egui.

**Comment by ijsnow** [comment]
Awesome, thanks!
