### ISSUE TITLE
triggers hotkey outside of the application   cannot obtain the corresponding event

### ISSUE THREAD

**Issue by git-xxing** [amrbashir/global-hotkey#31]
In the example egui, when I press a hotkey outside the window, the application does not immediately print the GlobalHotKeyEvent. When I return to the application window, it will print all events simultaneously.

**Comment by amrbashir** [comment]
This is because the listening logic is done in the window render loop, if you move the listener to its own thread or if egui has some other loop that is not specific to the window, it will work.

I will see if I can update the example sometime soon.

**Comment by git-xxing** [comment]
if i move the listener to its own thread ,will it be affected by the following?
 > On Windows a win32 event loop must be running on the thread. It doesn't need to be the main thread but you have to create the global hotkey manager on the same thread as the event loop.
On macOS, an event loop must be running on the main thread so you also need to create the global hotkey manager on the main thread.

**Comment by amrbashir** [comment]
No the receiver can be moved to another thread no problem, but the GlobalHotkeyManager can't be.
