### ISSUE TITLE
feat: support `Backquote` key

### ISSUE THREAD

**Issue by melMass** [amrbashir/global-hotkey#41]
Hi,

I'm trying to debug the proper keycode for the key at the left of the `1` in the top row of an azerty keyboard.
I tried `Backslash` (this is mapped to `><`), `Backquote` (this is mapped to the proper backquote on azerty), and a few others that failed to register altogether.
Is there a way to register all supported keycodes in order to debug that?

Thanks for the lib really useful and it also integrates well with slint-ui

**Comment by amrbashir** [comment]
There is a lot of keys that we don't support out of the box and hopefully we can add gradually.

I did some research and found the keys that we need to use:
Windows: `VK_OEM_3` https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
Linux (X11): `XK_quoteleft` https://docs.rs/x11-dl/latest/x11_dl/keysym/constant.XK_quoteleft.html 

@pewsheen can you check what is the code for `Backquote` on macOS?

**Comment by pewsheen** [comment]
> There is a lot of keys that we don't support out of the box and hopefully we can add gradually.
> 
> I did some research and found the keys that we need to use: Windows: `VK_OEM_3` https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes Linux (X11): `XK_quoteleft` https://docs.rs/x11-dl/latest/x11_dl/keysym/constant.XK_quoteleft.html
> 
> @pewsheen can you check what is the code for `Backquote` on macOS?

Should be `kVK_ANSI_Grave (0x32)`

**Comment by amrbashir** [comment]
Looks like we already support this key on Windows and macOS, what platform did you test this on? or does it work on some layouts while others don't?

**Comment by melMass** [comment]
> Looks like we already support this key on Windows and macOS, what platform did you test this on? or does it work on some layouts while others don't?

- I tried on an AZERTY Mac keyboard but I can check on an AZERTY windows in a few (there it's the ˋ²ˋ key on AZERTY)

- French layouts

**Comment by amrbashir** [comment]
I see, I think that's the expected behavior when you change layout. Windows also behaves this way, so I will go ahead and add the key to Linux as well and then I will mark this issue as solved.
