### ISSUE TITLE
Dummy drivers for non mac/win/linux projects

### ISSUE THREAD

**Issue by jkelleyrtp** [amrbashir/global-hotkey#63]
Even though this crate doesn't work on Android/iOS/etc, that doesn't mean the types of this crate can't be exposed on those platforms.

I don't see why any of the types in lib.rs couldn't work across all the platforms, even if functionality didn't work. Having to work around this is a bit of a nuisance since it needs we need to wrap the type or stub it out - neither of which are great.

**Comment by amrbashir** [comment]
Should these dummy driver return an `Err(Unsupported)` or return with an `Ok(())`?.

**Comment by jkelleyrtp** [comment]
For the sake of integration I would prefer Ok(()) since there's no errors that would be generated by using a dummy handler.

Alternatively, returning an error is fine provided the errors don't infect the rest of the codebase (IE returning Self shouldn't fail, since you want a handler on every platform, even if it is a dummy).

**Comment by jkelleyrtp** [comment]
That was quick! Thanks!!
