### ISSUE TITLE
Windows modifier codes failed to register

### ISSUE THREAD

**Issue by temportalflux** [amrbashir/global-hotkey#86]
HotKeyCode's Shift, Control, Alt, Meta (all Left and Right), as well as Pause (as in PauseBreak) fail to register on windows.
`FailedToRegister("Unable to register hotkey (unknown VKCode for this key: ShiftLeft).")`

It appears they are not supported as direct bindings via in `key_to_vk`
https://github.com/tauri-apps/global-hotkey/blob/91373c8f66b67c457efd521568d11ece9070d47c/src/platform_impl/windows/mod.rs#L188

Tried to work around this by adding a hotkey with the corresponding modifier code using Unidentified as the vk_code, but that didnt not successfully register either.

**Comment by amrbashir** [comment]
These keys are reserved for modifiers and can't be used as main key. I will add support for Pause key though.
