### ISSUE TITLE
Input events are always consumed

### ISSUE THREAD

**Issue by temportalflux** [amrbashir/global-hotkey#87]
The documentation doesn't indicate that registering events consumes the input, but listening for hotkeys does just that. I'd love the ability to specify that the hotkey manager should never consume input for my use-case.

**Comment by amrbashir** [comment]
This is not how hotkeys work unfortunately. I think what you're looking for is something like https://docs.rs/rdev/latest/rdev/

**Comment by sincekmori** [comment]
If the key you wanted left unconsumed is specifically Ctrl+C, meaning a copy-triggered workflow, I built a crate on the listen-only approach @amrbashir pointed to: [copycopy](https://github.com/sincekmori/copycopy). A single Ctrl+C passes through untouched, and pressing `C` twice while holding the modifier is the trigger. It also works around rdev's macOS off-main-thread crash by using its own `CGEventTap`.
